### ISSUE TITLE
Invalid memory address error when running Launchpad prior to registering

### ISSUE THREAD

**Issue by javajason** [Mirantis/launchpad_legacy#32]
If you attempt to run launchpad prior to registering as a user, some commands will trigger an "invalid memory address" error, followed by a stack trace.

Example:
```
$ launchpad apply
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x848a01]

goroutine 1 [running]:
github.com/Mirantis/mcc/pkg/analytics.(*Client).TrackEvent(0xf1adb0, 0xa1c100, 0x13, 0xc0002d44e0, 0xc00005fc20, 0xc00005fc00)
	/go/src/github.com/Mirantis/mcc/pkg/analytics/analytics.go:74 +0x291
github.com/Mirantis/mcc/pkg/analytics.(*Client).RequireRegisteredUser(0xf1adb0, 0xa18d07, 0xe)
	/go/src/github.com/Mirantis/mcc/pkg/analytics/user.go:12 +0x5a
github.com/Mirantis/mcc/pkg/analytics.RequireRegisteredUser(...)
	/go/src/github.com/Mirantis/mcc/pkg/analytics/analytics.go:119
github.com/Mirantis/mcc/cmd.NewApplyCommand.func1(0xc000288c80, 0x3, 0x4)
	/go/src/github.com/Mirantis/mcc/cmd/apply.go:32 +0x69
github.com/urfave/cli/v2.(*Command).Run(0xc0000a6d80, 0xc000288a80, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:151 +0x57c
github.com/urfave/cli/v2.(*App).RunContext(0xc0001b4300, 0xaee020, 0xc00001e5c8, 0xc00000c080, 0x2, 0x2, 0x0, 0x0)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x790
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/go/src/github.com/Mirantis/mcc/main.go:82 +0x67f
```
The same behavior ("invalid memory address" and stack trace) is seen when running the _reset_ command without registering.
This gives very little indication of the real underlying issue, and will only confuse users. Instead, this error should be handled in the code, and a clear error message should be provided.

By contrast, the _init_ command, when the user has not yet registered, outputs a much more useful error message:
```
$ launchpad init
FATA[0000] Registration or license acceptance is required. Please use `launchpad register` command to register
```
This is very clear what the specific problem is and what is required to correct it.

**Comment by jakolehm** [comment]
This was fixed in 0.12.1.
